mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pybo.urls'))
]

mysite/pybo/urls.py
from django.urls import path
from . import views
app_name = 'pybo'

urlpatterns =[
    path('',views.main, name = 'main'),
    path('<title>',views.quiz1, name = 'q'),
    #path('<det>',views.render_quiz, name='quiz'),
    path('<det>/<d>',views.render_quiz, name='quiz')
]

mysite/pybo/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Quiz(models.Model):
    title = models.CharField(max_length=200, primary_key=True)
    def __str__(self):
        return self.title

class D(models.Model):
    tit = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    ques = models.CharField(max_length=30)
    content1 = models.TextField()
    content2 = models.TextField()
    content3 = models.TextField()
    content4 = models.TextField()
    def __str__(self):
        return str(self.tit)

mysite/pybo/forms.py
from django import forms
from pybo.models import Question, Answer, Comment
class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']
        labels = {
            'subject': '제목',
            'content': '내용',
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content': '댓글내용',
        }

mysite/pybo/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
#from .forms import QuestionForm, AnswerForm
from django.utils import timezone
from .models import *
# Create your views here.

def main(request):
    quiz = Quiz.objects.all()
    quiz_list = {'quiz': quiz}
    return render(request, 'main.html', quiz_list)

def quiz1(request,title):
    det = D.objects.filter(tit = title, id = 1)
    det_list = {'det': det}
    return render(request, 'quiz1.html', det_list)

def render_quiz(request, det, d):
    dd = get_object_or_404(D,id=det)
    det= int(det)+1
    d2 = get_object_or_404(D,id=det)
    return render(request, 'quiz1-1.html', {'det': dd, 'det2':d2})

mysite/pybo/templates/base.html
    {% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>DEV!</title>
</head>
<body>
    {% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->

<!-- jQuery JS -->
<script src="{% static 'jquery-3.5.1.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
</body>
</html>

mysite/pybo/templates/main.html
{% extends 'base.html' %}
{% block content %}
{%   for q in quiz %}
<form action="{% url 'pybo:q' q.title %}">
    <input type="submit" value="{{q}}">
</form>
{% endfor %}
{% endblock %} 

mysite/pybo/templates/quiz1-1.html
{% extends 'base.html' %}
{% block content %}

<h1>{{det.tit}}</h1>
<h2>{{det.ques}}</h2>
<h2>{{det.id}}/10 </h2>

<form action="{% url 'pybo:quiz' det2.id det %}">
    {% csrf_token %}
    <input type="submit" value="{{det.content1}}">
</form>
<form action="{% url 'pybo:quiz' det2.id det%}">
    {% csrf_token %}
    <input type="submit" value="{{det.content2}}">
</form>
<form action="{% url 'pybo:quiz' det2.id det%}">
    {% csrf_token %}
    <input type="submit" value="{{det.content3}}">
</form>
<form action="{% url 'pybo:quiz' det2.id det%}">
    {% csrf_token %}
    <input type="submit" value="{{det.content4}}">
</form>

{% endblock %}

mysite/pybo/templates/quiz1.html
{% extends 'base.html' %}
{% block content %}

{% for d in det %}
<h1>{{d.tit}}</h1>
<form action="{% url 'pybo:quiz' d.id d%}">
    <input type="submit" value="시작하기">
</form>

{% endfor %}    
{% endblock %}

mysite/pybo/templates/quiz1_1.html
{% extends 'base.html' %}
{% block content %}

<h1>{{det.tit}}</h1>
<h2>{{det.ques}}</h2>
<h3>{{det.id}}</h3>
<form action="{% url 'pybo:quiz' det2.id det %}">
    {% csrf_token %}
    <input type="submit" value="{{det.content1}}">
</form>
<form action="{% url 'pybo:quiz' det2.id det%}">
    {% csrf_token %}
    <input type="submit" value="{{det.content2}}">
</form>
<form action="{% url 'pybo:quiz' det2.id det%}">
    {% csrf_token %}
    <input type="submit" value="{{det.content3}}">
</form>
<form action="{% url 'pybo:quiz' det2.id det%}">
    {% csrf_token %}
    <input type="submit" value="{{det.content4}}">
</form>

{% endblock %}

mysite/pybo/templates/test.html
테스트

mysite/templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

mysite/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'pybo:main' %}">DEV</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">

        </ul>
    </div>
</nav>

mysite/templates/pybo/comment_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <h5 class="border-bottom pb-2">댓글등록하기</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">댓글내용</label>
            <textarea class="form-control"name="content" id="content" 
                      rows="3">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

mysite/templates/pybo/question_detail.html
{% extends 'base.html' %}
{% block content %}

{% endblock %}

mysite/templates/pybo/question_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
    <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

mysite/templates/pybo/quiz/quiz1/quiz1-2.html
{% extends 'base.html' %}
{% block content %}
<form action="./quiz1-3">
    {% csrf_token %}
    <input type="button" value="{{example1_5}}">
    <br>
    <input type="button" value="{{example1_6}}">
    <br>
    <input type="button" value="{{example1_7}}">
    <br>
    <input type="button" value="{{example1_8}}">
</form>
{% endblock %}

mysite/templates/pybo/quiz/quiz1/quiz1-3.html
{% extends 'base.html' %}
{% block content %}
<form action="./quiz1-3">
    {% csrf_token %}
    <input type="button" value="{{example1_9}}">
    <br>
    <input type="button" value="{{example1_10}}">
    <br>
    <input type="button" value="{{example1_11}}">
    <br>
    <input type="button" value="{{example1_12}}">
</form>
{% endblock %}

mysite/templates/pybo/quiz/quiz1/quiz1-4.html
{% extends 'base.html' %}
{% block content %}
<form action="./quiz1-3">
    {% csrf_token %}
    <input type="button" value="{{example1_13}}">
    <br>
    <input type="button" value="{{example1_14}}">
    <br>
    <input type="button" value="{{example1_15}}">
    <br>
    <input type="button" value="{{example1_16}}">
</form>
{% endblock %}